import localFont from "next/font/local";
import { Manrope } from "next/font/google";
import "./globals.css";

// Define fonts and link to CSS variables
const ateoric = localFont({
  src: "../public/fonts/Aldridge.ttf",
  variable: "--font-ateoric",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ateoric.variable} ${manrope.variable}`}>
      <body>{children}</body>
    </html>
  );
}
